package config

import (
	"fmt"
	"strings"

	"github.com/northcutted/clearcutt-verify/internal/versionpolicy"
)

// CompiledCell is one resolved (runtime line, tier) image cell in the fleet
// matrix — the unit the flake builds.
type CompiledCell struct {
	Line      string // runtime line id, e.g. "java21", "coreLTS"
	Language  string
	Version   string
	Tier      string
	Lifecycle versionpolicy.Lifecycle
}

// CompiledMatrix is the resolved build set compiled from a fleet config. It is
// the data the flake reads in place of deriving the image matrix from
// registry.nix — the hardened per-runtime recipes stay curated in registry.nix;
// this is only the enumeration of which cells exist and which gates cover them.
type CompiledMatrix struct {
	Systems              []string
	Tiers                []string
	Cells                []CompiledCell
	ClosurePurityTargets []string
}

// CompileMatrix resolves matrix.languages × matrix.tiers into concrete image
// cells, stamping each with its lifecycle from the shared version policy, and
// derives the realized-closure gate target lists. includePreview (from
// --allow-preview) unions preview-channel runtimes when the matrix uses the
// language-level form; the legacy explicit form ignores it.
//
// Gate targets are default-INCLUDE: every production tier (slim/distroless) of
// every line that ships a production runtime is gated. A line is excluded only
// when the policy explicitly marks its language omitInProduction (toolchain
// lines that ship no runtime in production). This guarantees the generated
// coverage is a superset of any hand-maintained deny list — generation can only
// ever add coverage, never silently drop a tier.
func (c Config) CompileMatrix(includePreview bool) (CompiledMatrix, error) {
	lines, err := c.Matrix.ResolveRuntimeLines(includePreview)
	if err != nil {
		return CompiledMatrix{}, err
	}

	cells := make([]CompiledCell, 0, len(lines)*len(c.Matrix.Tiers))
	for _, line := range lines {
		info, ok := c.RuntimeLineInfo(line)
		if !ok {
			return CompiledMatrix{}, fmt.Errorf("matrix.languages entry %q is not a supported runtime line", line)
		}
		for _, tier := range c.Matrix.Tiers {
			cells = append(cells, CompiledCell{
				Line:      line,
				Language:  info.Language,
				Version:   info.Version,
				Tier:      tier,
				Lifecycle: versionpolicy.LifecycleFor(line, tier),
			})
		}
	}

	closurePurity := deriveGateTargets(lines, c.Matrix.Tiers)

	return CompiledMatrix{
		Systems:              append([]string(nil), c.Matrix.Systems...),
		Tiers:                append([]string(nil), c.Matrix.Tiers...),
		Cells:                cells,
		ClosurePurityTargets: closurePurity,
	}, nil
}

// deriveGateTargets builds the realized-closure gate target lists in runtime-
// line order. closurePurity covers production distroless images (no shells /
// package managers / setuid); runtimePatch covers every production tier (slim +
// distroless) that ships an openssl/sqlite-linked runtime.
// deriveGateTargets returns the realized-closure gate targets: every production
// distroless image. The slim tier was also gated when runtime-patch completeness
// existed; that gate retired with runtime-scoped CVE patching, and closure-purity
// only applies to distroless (the slim tier ships a shell by contract).
func deriveGateTargets(lines, tiers []string) (closurePurity []string) {
	if !containsTier(tiers, "distroless") {
		return nil
	}
	for _, line := range lines {
		if !versionpolicy.ShipsProductionRuntime(line) {
			continue
		}
		closurePurity = append(closurePurity, line+"-distroless")
	}
	return closurePurity
}

func containsTier(tiers []string, want string) bool {
	for _, t := range tiers {
		if t == want {
			return true
		}
	}
	return false
}

// RenderMatrixNix renders a CompiledMatrix as the generated core/lib/
// fleet-matrix.nix. The output is deterministic for a given config so the
// `clearcutt-verify fleet compile --check` byte-compare can gate drift.
func RenderMatrixNix(m CompiledMatrix) string {
	var b strings.Builder
	b.WriteString("# Generated by `clearcutt-verify fleet compile` from clearcutt.fleet.yaml.\n")
	b.WriteString("# Resolved fleet build set: the concrete (language, version, tier) image\n")
	b.WriteString("# cells, their lifecycle, and the realized-closure gate targets. This file is\n")
	b.WriteString("# DATA, not logic — the hardened per-runtime recipes stay in lib/registry.nix.\n")
	b.WriteString("# Do not edit by hand; regenerate with `clearcutt-verify fleet compile`. CI fails on\n")
	b.WriteString("# drift via `clearcutt-verify fleet compile --check`.\n\n")
	b.WriteString("{\n")
	fmt.Fprintf(&b, "  systems = %s;\n", nixStringList(m.Systems))
	fmt.Fprintf(&b, "  tiers = %s;\n\n", nixStringList(m.Tiers))

	b.WriteString("  cells = [\n")
	for _, cell := range m.Cells {
		fmt.Fprintf(&b,
			"    { line = %q; language = %q; version = %q; tier = %q; lifecycle = { status = %q; support = %q; productionAllowed = %s; }; }\n",
			cell.Line, cell.Language, cell.Version, cell.Tier,
			cell.Lifecycle.Status, cell.Lifecycle.Support, nixBoolLiteral(cell.Lifecycle.ProductionAllowed),
		)
	}
	b.WriteString("  ];\n\n")

	b.WriteString("  closurePurityTargets = [\n")
	for _, target := range m.ClosurePurityTargets {
		fmt.Fprintf(&b, "    %q\n", target)
	}
	b.WriteString("  ];\n")

	b.WriteString("}\n")
	return b.String()
}

func nixStringList(values []string) string {
	parts := make([]string, 0, len(values))
	for _, v := range values {
		parts = append(parts, fmt.Sprintf("%q", v))
	}
	return "[ " + strings.Join(parts, " ") + " ]"
}

func nixBoolLiteral(v bool) string {
	if v {
		return "true"
	}
	return "false"
}
